### ISSUE TITLE
apt apk logic

### ISSUE THREAD

**Issue by xuijuthub** [ConzZah/Alice-Madness-Returns-Patcher_Linux#1]
apt, apk are not the only package managers in Linux, and other UNIX-likes world. It would be a better approach to check if bin of apt or apk exists to determine the package manager for installation of package, rather than == "$DISTR_NAME"

f. e. redhat has `yum install`, fedora `dnf install`, archlinux `pacman -S`, freebsd `pkg install`
at the beginning of the script find and print which binaries are missing (let's say - 7z, base64, wget), then if  neither apt, apk bins does not return a match - exit - so user can install them manually in their familiar environment

**Comment by ConzZah** [comment]
hey i adressed your issue in [v3.4](https://github.com/ConzZah/Alice-Madness-Returns-Patcher_Linux/commit/fdf66bfd45941c25900af22457e26737cb9dab16) thanks for telling me btw, appreciate it. 

https://github.com/ConzZah/Alice-Madness-Returns-Patcher_Linux/blob/fdf66bfd45941c25900af22457e26737cb9dab16/ALICE_MADNESS_RETURNS_PATCHER_latest.sh#L87-L94
